version: "3.9"

services:
  nestjs:
    build: .
    container_name: nestjs-template
    volumes:
      - .:/usr/src/app
    ports: 
      - "3000:3000"
    env_file:
      - .env
    command: "npm run start:dev"

  nestjs-postgres:
    container_name: nestjs-postgres
    image: postgres
    volumes:
      - pg-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    env_file: 
      - .env
    restart: always

  nestjs-pgadmin:
    container_name: nestjs-pgadmin
    image: dpage/pgadmin4
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    ports:
      - "5050:80"
    env_file:
      - .env
    restart: always

volumes:
  pg-data:
  pgadmin-data: